Update patch set 1
Patch Set 1:

Build fails with missing #include <time.h>;

external/nano/src/search.c:188:23: error: implicit declaration of function 'time' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        time_t lastkbcheck = time(NULL);

Patch-set: 1
CC: Gerrit User 12604 <12604@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>